import type { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://www.bestgoa.com'

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/admin/*',
          '/api/',
          '/api/*',
          '/auth/',
          '/auth/*',
          '/dashboard/',
          '/dashboard/*',
          '/favorites/',
          '/favorites/*',
          '/itineraries/',
          '/itineraries/*',
          '/submissions/',
          '/submissions/*',
          '/settings/',
          '/settings/*',
          '/login',
          '/_next/',
          '/_next/*',
        ],
      },
      {
        // OpenAI's crawler (ChatGPT, SearchGPT)
        userAgent: 'GPTBot',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
          '/application',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/', '/auth/'],
      },
      {
        // Anthropic's crawler (Claude)
        userAgent: 'anthropic-ai',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
      {
        // Anthropic's ClaudeBot
        userAgent: 'ClaudeBot',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
      {
        // Google's AI crawler (Gemini)
        userAgent: 'Google-Extended',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
      {
        // Perplexity AI crawler
        userAgent: 'PerplexityBot',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
      {
        // Common Crawl (used by many AI models)
        userAgent: 'CCBot',
        allow: [
          '/',
          '/places-to-eat/',
          '/places-to-eat/*',
          '/places-to-stay/',
          '/places-to-stay/*',
          '/places-to-shop/',
          '/places-to-shop/*',
          '/places-to-visit/',
          '/places-to-visit/*',
          '/places-to-learn/',
          '/places-to-learn/*',
          '/things-to-do/',
          '/things-to-do/*',
          '/about',
          '/contact',
        ],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
